# Generated by Django 5.2.1 on 2025-05-23 15:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoodCategoryTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the food category (e.g., Fruits, Vegetables, Grains)', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='Brief description of the food category', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this category is currently active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Food Category',
                'verbose_name_plural': 'Food Categories',
                'db_table': 'food_category',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FoodTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the food item (e.g., Apple, Brown Rice)', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Additional description or notes about the food item', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this food item is currently active')),
                ('is_organic', models.BooleanField(default=False, help_text='Whether this is an organic food item')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(help_text='Category this food belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='foods', to='food_management.foodcategorytable')),
            ],
            options={
                'verbose_name': 'Food Item',
                'verbose_name_plural': 'Food Items',
                'db_table': 'food_item',
                'ordering': ['name'],
                'unique_together': {('name', 'category')},
            },
        ),
    ]
